# Generated by Django 2.2.5 on 2021-02-17 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('日記', '日記'), ('お得情報', 'お得情報'), ('お知らせ', 'お知らせ'), ('その他', 'その他')], max_length=200, null=True, verbose_name='じゃんる')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='制作日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='発表日')),
            ],
            options={
                'verbose_name': 'ニュース',
                'verbose_name_plural': 'ニュース',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='タイトル', max_length=200)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, default='本文', max_length=100000, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='制作日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='発表日')),
            ],
            options={
                'verbose_name': 'メニュー',
                'verbose_name_plural': 'メニュー',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='名前')),
                ('text', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='制作日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='発表日')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'verbose_name_plural': 'プロフィール',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='店名')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='表示名')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.Store', verbose_name='店舗')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ログインユーザー')),
            ],
            options={
                'verbose_name': 'スタッフ',
                'verbose_name_plural': 'スタッフ',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(verbose_name='終了時間')),
                ('name', models.CharField(max_length=255, verbose_name='予約者名')),
                ('email', models.CharField(default='メールアドレス@', max_length=255, verbose_name='メールアドレス')),
                ('number', models.CharField(blank=True, default='電話番号', max_length=255, null=True, verbose_name='電話番号')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.Staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': 'スケジュール',
                'verbose_name_plural': 'スケジュール',
            },
        ),
        migrations.CreateModel(
            name='PictureForProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictureforprofile', to='museum.Profile')),
            ],
            options={
                'verbose_name': 'ブログ写真',
                'verbose_name_plural': 'ブログ写真',
            },
        ),
        migrations.CreateModel(
            name='PictureForPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictureforpost', to='museum.Post')),
            ],
            options={
                'verbose_name': 'ニュース写真',
                'verbose_name_plural': 'ニュース写真',
            },
        ),
        migrations.CreateModel(
            name='PictureForNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avator', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picturefornews', to='museum.News')),
            ],
            options={
                'verbose_name': 'メニュー写真',
                'verbose_name_plural': 'メニュー写真',
            },
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('user', 'store'), name='unique_staff'),
        ),
    ]
