# Generated by Django 3.1.5 on 2021-02-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picturefornews',
            options={'verbose_name': 'ニュース写真', 'verbose_name_plural': 'ニュース写真'},
        ),
        migrations.AlterModelOptions(
            name='pictureforpost',
            options={'verbose_name': 'メニュー写真', 'verbose_name_plural': 'メニュー写真'},
        ),
    ]
