# Generated by Django 3.1.5 on 2021-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_auto_20210225_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='genre',
            field=models.CharField(blank=True, choices=[('日記', '日記'), ('お得情報', 'お得情報'), ('お知らせ', 'お知らせ'), ('その他', 'その他')], max_length=200, null=True, verbose_name='ジャンル'),
        ),
    ]
